### ISSUE TITLE
BUG: One for all

### ISSUE THREAD

**Issue by Fenaldar** [Symon-S/FoundryVTT-Macros#11]
Hello,
the macro "One_for_all" don't work here:

Unsupported modifier object (slug: cha) passed
Unsupported modifier object (slug: proficiency) passed

Foundry V 11.315

**Comment by Symon-S** [comment]
Fixed by https://github.com/Symon-S/FoundryVTT-Macros/commit/469586bc7305a71bf5ab1f6b7185220801784ab2
