### ISSUE TITLE
Dice So Nice disabled client-side with "Treat Wounds and Battle Medicine" macro

### ISSUE THREAD

**Issue by kruvek** [Symon-S/FoundryVTT-Macros#12]
When Dice So Nice is disabled on the client side, we're getting weird behavior with the "Treat Wounds and Battle Medicine" macro, as well as with the "Treat Wounds" macro inside of Basic Actions Macro.  This behavior is not replicated with the standard "Treat Wounds" macro included with the system.

Behavior:
When triggering the macro, it rolls the medicine check and then stops.  If you trigger the macro a 2nd time, it rolls the medicine check, then rolls the healing rolls for both checks and displays them.  No errors in the console.

Reenabling Dice So Nice for the client removes this issue (they have it disabled because they're on a potato pc).

**Comment by Symon-S** [comment]
Not one of my personal macros, but I have informed the creator of the macro of this issue.

**Comment by Symon-S** [comment]
@kruvek 
https://gitlab.com/symonsch/my-foundryvtt-macros/-/issues/50
